### ISSUE TITLE
Pattern to search for files in directory and its subdirectories is not possible

### ISSUE THREAD

**Issue by stijnvancrombrugge** [michael-doubez/filestat_exporter#10]
We want to be able to list all files matching a certain pattern in a directory or subdirectories of that directory. This is not possible in the current situation. Something like ** which works for Python globs would be a nice feature. For example when using "test/**/*.txt" as a pattern, this would look for all .txt files in the test directory and all its subdirectories.

**Comment by michael-doubez** [comment]
I considered it when writing the first version but though that it would be overkill since we usually want to keep a hold on the cardinality of the metrics.

In the meantime, one can use various depth of '*/*/.../*.txt' and I didn't think it too much of a burden.

Do you have a use case were it would unpractical ?

**Comment by stijnvancrombrugge** [comment]
> I considered it when writing the first version but though that it would be overkill since we usually want to keep a hold on the cardinality of the metrics.
> 
> In the meantime, one can use various depth of '_/_/.../*.txt' and I didn't think it too much of a burden.
> 
> Do you have a use case were it would unpractical ?

For example when you have a server and you want to monitor the files passing the system through a certain directory. If a new folder is made in this directory and files are put in there, we never know this, because those metrics won't be exported.

**Comment by michael-doubez** [comment]
Right. It makes sense.
Let add support for doublestar.

**Comment by michael-doubez** [comment]
Delivered in version v0.3.3
