### ISSUE TITLE
File owner information

### ISSUE THREAD

**Issue by ravi-visionet** [michael-doubez/filestat_exporter#22]
Hi,

Appreciate the filestat exporter.

Would it be possible to get owner of the file?

Thanks
Ravi

**Comment by michael-doubez** [comment]
Hello,

What are you trying to monitor ?


This would be tricky to make work on non-posix system (windows).

Let say we restrict it to POSIX systems, there are two options:

1. Display system info (user, group ...) as an info metric: info would be in the label.
    Note: the value would be the timestamp of the file because any chmod on the file would duplicate the metric [during the staleness time](https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness) (~5min)
    ```
    filestat_file_info{file="a_file.txt",user="me",group="friends"} <timestamp of file>
    ```
2. Expose system info as a gauge metric: uid if the value of the metric (effective name of the user could be exposed in another metrics)
   ```
    filestat_file_uid{file="a_file.txt"}  42
    filestat_user_uid{name="me"} 42
    ```

I'd rather choose the option 2 since I could always use uid as an index on windows.

**Comment by ravi-visionet** [comment]
> Hello,
> 
> What are you trying to monitor ?
> 
> This would be tricky to make work on non-posix system (windows).
> 
> Let say we restrict it to POSIX systems, there are two options:
> 
> 1. Display system info (user, group ...) as an info metric: info would be in the label.
>    Note: the value would be the timestamp of the file because any chmod on the file would duplicate the metric [during the staleness time](https://prometheus.io/docs/prometheus/latest/querying/basics/#staleness) (~5min)
>    ```
>    filestat_file_info{file="a_file.txt",user="me",group="friends"} <timestamp of file>
>    ```
> 2. Expose system info as a gauge metric: uid if the value of the metric (effective name of the user could be exposed in another metrics)
>    ```
>     filestat_file_uid{file="a_file.txt"}  42
>     filestat_user_uid{name="me"} 42
>    ```
> 
> I'd rather choose the option 2 since I could always use uid as an index on windows.

Hi Michael,

Thanks for the details.

The goal is to monitor Linux & windows files ( size, last modified/accessed, owner of the file)

I am trying to monitor the Owner and Group of the specific file/folder. Currently I am able to monitor only file size and last modified info.

Please refer the below Grafana widget, is there any way that we can get the owner and group details as well.

<img width="740" alt="file" src="https://user-images.githubusercontent.com/88369717/139811232-c516ba4d-38ae-4fe1-9e8f-e87ef7ddff8b.PNG">

**Comment by kverma95** [comment]
@ravi-visionet , Can you share the json file ?

**Comment by michael-doubez** [comment]
Too old
