### ISSUE TITLE
Monitornig of file backup

### ISSUE THREAD

**Issue by deepak7340** [michael-doubez/filestat_exporter#26]
Is there a way to monitor file backup availabe for last 24 hrs. 
Since i was trying with

```
time() - file_stat_modif_time_seconds{instance="server:63387"} < 86400
```
- This expression will list the files which are avaliable in last 24 hours. But how can i alert which all files are not available in last 24 hrs.

**Comment by michael-doubez** [comment]
Hello,

This question would more more sense on stackoverflow.

The exporter can only gives you the files it has access to. It has no way to know if a file is missing.

The expression you gave gives you the files that were modified within the last 24h.

If you have metrics on the `live` files, you can check that the live files that have been modified within the last 24h have a backup less then 24h (assuming the path are the same - overwise you need to relabel them).

    file_stat_modif_time_seconds{instance="live:63387"} - ON(path) file_stat_modif_time_seconds{instance="backup:63387"} < 24*3600

If you have a limited number of expected files you can define a rule for each file:

    ABSENT(file_stat_modif_time_seconds{instance="server:63387", path=~".*/my-file.tgz"})
