### ISSUE TITLE
Make it possible to enable/disable specific metrics in configuration file

### ISSUE THREAD

**Issue by Mesmerizzle** [michael-doubez/filestat_exporter#30]
I'm using this exporter mostly to keep an eye on the number of files in a specific folder, and it works beautifully. 

However, I don't need to have the file size of modified date to be recorded for every file that appears in a folder. 

For folders that are used heavily this generates a huge amount of metrics generated that are never used and put a some strain on our Prometheus installation. It might be useful to have the ability to enable/disable specific metrics from being generated for use cases like this.

**Comment by michael-doubez** [comment]
Metrics are currently only generated for files but metrics per directory seems to be a popular demand 

I ll schedule the feature

**Comment by Mesmerizzle** [comment]
I see we can now enable/disable file_content_line_number and file_content_hash_crc32 via the config file. This looks exactly like what i'm looking for. 

Any chance you can also add this for file_stat_size_bytes and file_stat_modif_time_seconds. 

something like:
    - patterns: ["archives/*.tar.gz"]
      enable_size_bytes_metric: false
      enable_modif_time_metric: false

**Comment by michael-doubez** [comment]
There are options for crc32 and nbline because they don't always make sense but others are cheap.
For other metrics, you can filter them out in prometheus config at ingestion time.

**Comment by michael-doubez** [comment]
Please reopen if you think you have a valid use case
