### ISSUE TITLE
The 0.3.6 version starts to report an error

### ISSUE THREAD

**Issue by ilanni2460** [michael-doubez/filestat_exporter#31]
The 0.3.6 version starts to report an error

OS Version: CentOS Linux release 7.6.1810 (Core)

/usr/local/prometheus/filestat_exporter: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/prometheus/filestat_exporter)
/usr/local/prometheus/filestat_exporter: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/prometheus/filestat_exporter)
![error](https://user-images.githubusercontent.com/5058391/227911845-505a76f0-5169-4fc1-8655-b6024941c914.png)

**Comment by michael-doubez** [comment]
Hello. I ll recompiler it on an older system
https://utcc.utoronto.ca/~cks/space/blog/programming/GoAndGlibcVersioning

**Comment by ilanni2460** [comment]
@michael-doubez Yes, if you recompile it on the old OS, you can continue using it without errors. That's what I did, and it has been working fine for several days now.
