### ISSUE TITLE
Outdated docker hub version 

### ISSUE THREAD

**Issue by Gimli05** [michael-doubez/filestat_exporter#37]
Hi!

The docker hub image is still `v0.3.5` whereas the `v0.3.6` has already been released here.
Is there a possibility that you could update the docker hub image to `v0.3.6` as well?

**Comment by michael-doubez** [comment]
Done
https://hub.docker.com/layers/mdoubez/filestat_exporter/0.3.7/images/sha256-8f7bd01eb1dd219388894c5bdd7c1ce44cd016de120e4105a8f51224aa3452bd?context=repo

**Comment by Gimli05** [comment]
Thank you so much! 🏆

**Comment by Gimli05** [comment]
Hi!

Sorry for bothering you again, but the docker hub image is outdated once again (`v0.3.8` vs `v0.4.0`). Could you please update it?

**Comment by michael-doubez** [comment]
You are not bothering me.

I was in the process of publishing on dockerhub and quay but got sidetracked.
It is published now

**Comment by Gimli05** [comment]
Thank you!
