### ISSUE TITLE
Command Substitution

### ISSUE THREAD

**Issue by jonli662** [michael-doubez/filestat_exporter#38]
Nice exporter!
Is it possible to have shell expansions (command substitution) in the pattern of the config file?
I have tried but not got it to work.
If it isn't possible today, could you implement it?

For example to catch a file with todays date:

/tmp/*_\`date +%Y%m%d\`.log

**Comment by jonli662** [comment]
Any thoughts on this yet?

**Comment by michael-doubez** [comment]
I guess it is possible to have some templating but it won't be an open shell execution. It would be a huge security risk.

**Comment by jonli662** [comment]
Sounds great! Hope you can implement it, I'm afraid I don't have skills to contribute on this.

**Comment by michael-doubez** [comment]
@jonli662  The expression `/tmp/*_{{now.Local.Format "20060102"}}.log` should do the job with latest version
